[package]
name = "aspen"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.23.0", features = ["derive"]}
futures = {version = "0.3.31", features = ["executor"]}
nalgebra = "0.33.2"
tobj = {version = "4.0.3", features = ["async"]}
wgpu = "23.0.1"
winit = "0.30.7"
